# Generated by Django 5.0.2 on 2024-02-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_gallery_timeset_operationhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhour',
            name='timesets',
        ),
        migrations.AddField(
            model_name='operationhour',
            name='timesets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.timeset'),
        ),
    ]
