# Generated by Django 5.0.2 on 2024-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_operationhour_timesets_operationhour_timesets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='operationhour',
            options={'verbose_name': 'Operation Hour', 'verbose_name_plural': 'Operation Hours'},
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
