# Generated by Django 5.0.2 on 2024-02-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_gallery_options_alter_operationhour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram_link',
            field=models.URLField(),
        ),
    ]
