# Generated by Django 5.0.2 on 2024-02-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_contact_instagram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhour',
            name='timesets',
        ),
        migrations.AddField(
            model_name='operationhour',
            name='timesets',
            field=models.ManyToManyField(null=True, to='cms.timeset'),
        ),
    ]
