# Generated by Django 5.0.2 on 2024-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_operationhour_timesets_operationhour_timesets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhour',
            name='timesets',
            field=models.ManyToManyField(to='cms.timeset'),
        ),
    ]
